//pedir dos numeros y decir si son iguales o no
let num1 = 15;
let num2 = 10;
if (num1>num2) {
    console.log("es mayor el numero 1");
} else {
    console.log("es menor el numero 1");
}
//pedir un numero y indicar si es positivo o negativo
let numero3 = 2
if (numero3>= 0) {
    console.log("numero es negativo")
} else {
    console.log("nuemro es positivo")
}
//pedir un numero y decir si es par o impar
let numero4 = 55
if ("numero4 % 2 = 0") {
    console.log("es par")

}
    

 
    
